POST http://localhost:3000/symptoms
Content-Type: application/json

{
    "name": "Sleepy",
    "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
}