POST http://localhost:3000/activities
Content-Type: application/json

{
    "name": "Background Music",
    "duration": 30,
    "source": "https://www.youtube.com/watch?v=x6UITRjhijI",
    "preference": ["Mental", "Mindful", "Indoor", "Guided", "Calm Down"],
    "description": "-",
    "instructions": [
        {
            "step1": "listen to music",
            "step2": "listen to music",
            "step3": "repeat"
        }
    ],
    "benefits": ["616844ef3c07f79ac6384a18", "616845373c07f79ac6384a1a", "616d5791aa48709b0aeb1d79", "616d57b1aa48709b0aeb1d7b", "616d57bfaa48709b0aeb1d7d", "616d57caaa48709b0aeb1d7f"],
    "symptoms": ["616d66ec548a162738759372", "616d6705548a162738759375", "616d672b548a162738759379"]
}