POST http://localhost:3000/activities
Content-Type: application/json

{
    "name": "Water",
    "duration": 4,
    "source": "https://www.youtube.com/watch?v=GG5U0yJHX5o",
    "preference": ["Physical", "Mindless", "Indoor", "Self led", "Hype Up/Down"],
    "description": "Hydration",
    "instructions": [{
        "step1": "get a glass of crispy water out of the fridge",
        "step2": "drink it",
        "step3": "repeat",
    }],
    "benefits": ["616844ef3c07f79ac6384a18", "616845373c07f79ac6384a1a"],
    "symptoms": ["616846efb33d930dc6b0d731", "616846f8b33d930dc6b0d733", "616846feb33d930dc6b0d735"],
}